### ISSUE TITLE
Doesn't work with PowerBi embedded

### ISSUE THREAD

**Issue by Digit-89** [MicrosoftDocs/powerbi-docs.fr-fr#14]
This page is referred by [this one](https://docs.microsoft.com/en-us/dynamics365/portals/set-up-power-bi-integration), but URL parameter filters don't work with PowerBi embedded in a Microsoft Dynamics portal (neither PowerPortal).

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Filtrer un rapport à l’aide de paramètres de chaîne de requête dans l’URL - Power BI](https://docs.microsoft.com/fr-fr/power-bi/service-url-filters)
* Content Source: [powerbi-docs/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/service-url-filters.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srvbpigh** [comment]
Hello, @Digit-89
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #1472](https://github.com/MicrosoftDocs/powerbi-docs/issues/1472) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
Hello, @Digit-89 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerbi-docs/issues/1472.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
