### ISSUE TITLE
Featured question 

### ISSUE THREAD

**Issue by sosotheso** [MicrosoftDocs/powerbi-docs.fr-fr#27]
I want to know if powerbi generate itself the answer for our featured question, or we need to define the answer somewhere. thanks 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 9707e1ff-5927-e3e4-134d-8d2b04266f9c
* Version Independent ID: bec9f641-757c-b76f-4cee-c823c60222b4
* Content: [Création de questions exemplaires pour les Q&R de Power BI - Power BI](https://docs.microsoft.com/fr-fr/power-bi/create-reports/service-q-and-a-create-featured-questions#feedback)
* Content Source: [powerbi-docs/create-reports/service-q-and-a-create-featured-questions.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/create-reports/service-q-and-a-create-featured-questions.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srvbpigh** [comment]
Hello, @sosotheso
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @sosotheso, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerbi-docs/issues/2199. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team

**Comment by sosotheso** [comment]
Désolé, Je n'ai pas fait attention au fait que c'est un répertoire français . Merci
